# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Release APK
        # You may pin to the exact commit or the version.
        # uses: ShowMeThe/github_action_release@c03188563c3286ccd20cf0d2b1413a134e3cabc9
        uses: ShowMeThe/github_action_release@v0.01
        with:
          # Github secret token to allow automated publishing of APK to release.
          GITHUB_TOKEN: s



