name: Develop CI

on:
  push:
    branches-ignore: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build debug binary with Gradle
        uses: gradle/gradle-command-action@v2
        with:
          arguments: assembleDebug

      - uses: actions/upload-artifact@v2
        with:
          name: upload-apk
          path: ${{github.workspace}}/app/build/outputs/apk/debug/*.apk
